from setuptools import setup, find_packages
setup(name='vposer',
      version='0.1.0',
      packages=find_packages('vposer'),
      package_dir={'': 'vposer'},
      include_package_data=True,
      author='zzilch',
      author_email='zz@zilch.zone',
      maintainer='zzilch',
      maintainer_email='zz@zilch.zone',
      url='https://github.com/zzilch/vposer',
      description='Simple and clean vposer',
      long_description=open("README.md").read(),
      long_description_content_type="text/markdown",
      install_requires=["torch>=1.8.0","smplx>=0.1.28","pytorch3d>=0.3.0"],
      dependency_links=[],
      classifiers=[
          "Intended Audience :: Developers",
          "Intended Audience :: Researchers",
          "Natural Language :: English",
          "Operating System :: MacOS :: MacOS X",
          "Operating System :: POSIX",
          "Operating System :: POSIX :: BSD",
          "Operating System :: POSIX :: Linux",
          "Operating System :: Microsoft :: Windows",
          "Programming Language :: Python",
          "Programming Language :: Python :: 3",
          "Programming Language :: Python :: 3.7", ],
      )
